# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea47df3729e04be717d3a3d73c3ab47a19ca430058694be8a58bfe321f77ec4fb7224ea779f5b84bc2207b4d0fd97c001a1bf06f65e09724ec3c9564394abbd5

test:
  secret_key_base: e7a0fc08740845e2f5c7d89d84654fad45f82078ff61d1c2a2956ce458663281daf18d52f7335939949922d9764a048fcc84268a1390a9c87610922d4473061d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
